version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - DB_PATH=/app/data/exam-sync.db
    volumes:
      - ./backend/data:/app/data
      - /app/node_modules
    networks:
      - exam-sync-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - exam-sync-network
    restart: unless-stopped

networks:
  exam-sync-network:
    driver: bridge

volumes:
  db_data:
