services:
  - type: web
    name: exam-sync-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: DB_PATH
        value: /opt/render/project/src/backend/data/exam-sync.db
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: BCRYPT_ROUNDS
        value: 12
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
    disk:
      name: exam-sync-db
      mountPath: /opt/render/project/src/backend/data
      sizeGB: 1

  - type: web
    name: exam-sync-frontend
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: exam-sync-backend
          property: host
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
